syntax = "proto3";

package nimbuscore.v1;

option go_package = "github.com/gh0st-nemesis/nimbuscore/api/v1;v1";

service IdentityService {
  rpc RequestSVID(RequestSVIDRequest) returns (RequestSVIDResponse);
}

enum SVIDRole {
  SVID_ROLE_UNSPECIFIED = 0;
  SVID_ROLE_NODE = 1;
  SVID_ROLE_CONTROL_PLANE = 2;
}

message RequestSVIDRequest {
  string join_token = 1;
  bytes csr_der = 2;
  string node_name = 3;
  SVIDRole role = 4;
}

message RequestSVIDResponse {
  bytes cert_der = 1;
  bytes trust_bundle_der = 2;
}

service AdminService {
  rpc JoinRaft(JoinRaftRequest) returns (JoinRaftResponse);
}

message JoinRaftRequest {
  string node_id = 1;
  string raft_addr = 2;
}

message JoinRaftResponse {}
