// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cluster.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SVIDRole int32

const (
	SVIDRole_SVID_ROLE_UNSPECIFIED   SVIDRole = 0
	SVIDRole_SVID_ROLE_NODE          SVIDRole = 1
	SVIDRole_SVID_ROLE_CONTROL_PLANE SVIDRole = 2
)

// Enum value maps for SVIDRole.
var (
	SVIDRole_name = map[int32]string{
		0: "SVID_ROLE_UNSPECIFIED",
		1: "SVID_ROLE_NODE",
		2: "SVID_ROLE_CONTROL_PLANE",
	}
	SVIDRole_value = map[string]int32{
		"SVID_ROLE_UNSPECIFIED":   0,
		"SVID_ROLE_NODE":          1,
		"SVID_ROLE_CONTROL_PLANE": 2,
	}
)

func (x SVIDRole) Enum() *SVIDRole {
	p := new(SVIDRole)
	*p = x
	return p
}

func (x SVIDRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SVIDRole) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_proto_enumTypes[0].Descriptor()
}

func (SVIDRole) Type() protoreflect.EnumType {
	return &file_cluster_proto_enumTypes[0]
}

func (x SVIDRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SVIDRole.Descriptor instead.
func (SVIDRole) EnumDescriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{0}
}

type RequestSVIDRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	JoinToken string                 `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	// csr_der is a PKCS#10 CertificateRequest, DER-encoded, over an
	// ECDSA P-256 key generated locally — the private key never leaves
	// the requester.
	CsrDer        []byte   `protobuf:"bytes,2,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	NodeName      string   `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Role          SVIDRole `protobuf:"varint,4,opt,name=role,proto3,enum=nimbuscore.v1.SVIDRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSVIDRequest) Reset() {
	*x = RequestSVIDRequest{}
	mi := &file_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSVIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSVIDRequest) ProtoMessage() {}

func (x *RequestSVIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSVIDRequest.ProtoReflect.Descriptor instead.
func (*RequestSVIDRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *RequestSVIDRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *RequestSVIDRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *RequestSVIDRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RequestSVIDRequest) GetRole() SVIDRole {
	if x != nil {
		return x.Role
	}
	return SVIDRole_SVID_ROLE_UNSPECIFIED
}

type RequestSVIDResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CertDer        []byte                 `protobuf:"bytes,1,opt,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`
	TrustBundleDer []byte                 `protobuf:"bytes,2,opt,name=trust_bundle_der,json=trustBundleDer,proto3" json:"trust_bundle_der,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestSVIDResponse) Reset() {
	*x = RequestSVIDResponse{}
	mi := &file_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSVIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSVIDResponse) ProtoMessage() {}

func (x *RequestSVIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSVIDResponse.ProtoReflect.Descriptor instead.
func (*RequestSVIDResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *RequestSVIDResponse) GetCertDer() []byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

func (x *RequestSVIDResponse) GetTrustBundleDer() []byte {
	if x != nil {
		return x.TrustBundleDer
	}
	return nil
}

type JoinRaftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RaftAddr      string                 `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRaftRequest) Reset() {
	*x = JoinRaftRequest{}
	mi := &file_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRaftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRaftRequest) ProtoMessage() {}

func (x *JoinRaftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRaftRequest.ProtoReflect.Descriptor instead.
func (*JoinRaftRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRaftRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRaftRequest) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

type JoinRaftResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRaftResponse) Reset() {
	*x = JoinRaftResponse{}
	mi := &file_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRaftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRaftResponse) ProtoMessage() {}

func (x *JoinRaftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRaftResponse.ProtoReflect.Descriptor instead.
func (*JoinRaftResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{3}
}

var File_cluster_proto protoreflect.FileDescriptor

const file_cluster_proto_rawDesc = "" +
	"\n" +
	"\rcluster.proto\x12\rnimbuscore.v1\"\x96\x01\n" +
	"\x12RequestSVIDRequest\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12\x17\n" +
	"\acsr_der\x18\x02 \x01(\fR\x06csrDer\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12+\n" +
	"\x04role\x18\x04 \x01(\x0e2\x17.nimbuscore.v1.SVIDRoleR\x04role\"Z\n" +
	"\x13RequestSVIDResponse\x12\x19\n" +
	"\bcert_der\x18\x01 \x01(\fR\acertDer\x12(\n" +
	"\x10trust_bundle_der\x18\x02 \x01(\fR\x0etrustBundleDer\"G\n" +
	"\x0fJoinRaftRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\traft_addr\x18\x02 \x01(\tR\braftAddr\"\x12\n" +
	"\x10JoinRaftResponse*V\n" +
	"\bSVIDRole\x12\x19\n" +
	"\x15SVID_ROLE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSVID_ROLE_NODE\x10\x01\x12\x1b\n" +
	"\x17SVID_ROLE_CONTROL_PLANE\x10\x022g\n" +
	"\x0fIdentityService\x12T\n" +
	"\vRequestSVID\x12!.nimbuscore.v1.RequestSVIDRequest\x1a\".nimbuscore.v1.RequestSVIDResponse2[\n" +
	"\fAdminService\x12K\n" +
	"\bJoinRaft\x12\x1e.nimbuscore.v1.JoinRaftRequest\x1a\x1f.nimbuscore.v1.JoinRaftResponseB/Z-github.com/gh0st-nemesis/nimbuscore/api/v1;v1b\x06proto3"

var (
	file_cluster_proto_rawDescOnce sync.Once
	file_cluster_proto_rawDescData []byte
)

func file_cluster_proto_rawDescGZIP() []byte {
	file_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)))
	})
	return file_cluster_proto_rawDescData
}

var file_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cluster_proto_goTypes = []any{
	(SVIDRole)(0),               // 0: nimbuscore.v1.SVIDRole
	(*RequestSVIDRequest)(nil),  // 1: nimbuscore.v1.RequestSVIDRequest
	(*RequestSVIDResponse)(nil), // 2: nimbuscore.v1.RequestSVIDResponse
	(*JoinRaftRequest)(nil),     // 3: nimbuscore.v1.JoinRaftRequest
	(*JoinRaftResponse)(nil),    // 4: nimbuscore.v1.JoinRaftResponse
}
var file_cluster_proto_depIdxs = []int32{
	0, // 0: nimbuscore.v1.RequestSVIDRequest.role:type_name -> nimbuscore.v1.SVIDRole
	1, // 1: nimbuscore.v1.IdentityService.RequestSVID:input_type -> nimbuscore.v1.RequestSVIDRequest
	3, // 2: nimbuscore.v1.AdminService.JoinRaft:input_type -> nimbuscore.v1.JoinRaftRequest
	2, // 3: nimbuscore.v1.IdentityService.RequestSVID:output_type -> nimbuscore.v1.RequestSVIDResponse
	4, // 4: nimbuscore.v1.AdminService.JoinRaft:output_type -> nimbuscore.v1.JoinRaftResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cluster_proto_init() }
func file_cluster_proto_init() {
	if File_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_proto_depIdxs,
		EnumInfos:         file_cluster_proto_enumTypes,
		MessageInfos:      file_cluster_proto_msgTypes,
	}.Build()
	File_cluster_proto = out.File
	file_cluster_proto_goTypes = nil
	file_cluster_proto_depIdxs = nil
}
