// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: federation.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteCluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ApiAddr       string                 `protobuf:"bytes,2,opt,name=api_addr,json=apiAddr,proto3" json:"api_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteCluster) Reset() {
	*x = RemoteCluster{}
	mi := &file_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteCluster) ProtoMessage() {}

func (x *RemoteCluster) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteCluster.ProtoReflect.Descriptor instead.
func (*RemoteCluster) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteCluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RemoteCluster) GetApiAddr() string {
	if x != nil {
		return x.ApiAddr
	}
	return ""
}

type RegisterClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ApiAddr       string                 `protobuf:"bytes,2,opt,name=api_addr,json=apiAddr,proto3" json:"api_addr,omitempty"`
	JoinToken     string                 `protobuf:"bytes,3,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClusterRequest) Reset() {
	*x = RegisterClusterRequest{}
	mi := &file_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClusterRequest) ProtoMessage() {}

func (x *RegisterClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClusterRequest.ProtoReflect.Descriptor instead.
func (*RegisterClusterRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterClusterRequest) GetApiAddr() string {
	if x != nil {
		return x.ApiAddr
	}
	return ""
}

func (x *RegisterClusterRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

type UnregisterClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterClusterRequest) Reset() {
	*x = UnregisterClusterRequest{}
	mi := &file_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterClusterRequest) ProtoMessage() {}

func (x *UnregisterClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterClusterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterClusterRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UnregisterClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterClusterResponse) Reset() {
	*x = UnregisterClusterResponse{}
	mi := &file_federation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterClusterResponse) ProtoMessage() {}

func (x *UnregisterClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterClusterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterClusterResponse) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{3}
}

type ListClustersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersRequest) Reset() {
	*x = ListClustersRequest{}
	mi := &file_federation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersRequest) ProtoMessage() {}

func (x *ListClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersRequest.ProtoReflect.Descriptor instead.
func (*ListClustersRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{4}
}

type ListClustersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RemoteCluster       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClustersResponse) Reset() {
	*x = ListClustersResponse{}
	mi := &file_federation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClustersResponse) ProtoMessage() {}

func (x *ListClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClustersResponse.ProtoReflect.Descriptor instead.
func (*ListClustersResponse) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{5}
}

func (x *ListClustersResponse) GetItems() []*RemoteCluster {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListFederatedPodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFederatedPodsRequest) Reset() {
	*x = ListFederatedPodsRequest{}
	mi := &file_federation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFederatedPodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFederatedPodsRequest) ProtoMessage() {}

func (x *ListFederatedPodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFederatedPodsRequest.ProtoReflect.Descriptor instead.
func (*ListFederatedPodsRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{6}
}

func (x *ListFederatedPodsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type FederatedPods struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cluster       string                 `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Items         []*Pod                 `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FederatedPods) Reset() {
	*x = FederatedPods{}
	mi := &file_federation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederatedPods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederatedPods) ProtoMessage() {}

func (x *FederatedPods) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederatedPods.ProtoReflect.Descriptor instead.
func (*FederatedPods) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{7}
}

func (x *FederatedPods) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *FederatedPods) GetItems() []*Pod {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FederatedPods) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListFederatedPodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*FederatedPods       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFederatedPodsResponse) Reset() {
	*x = ListFederatedPodsResponse{}
	mi := &file_federation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFederatedPodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFederatedPodsResponse) ProtoMessage() {}

func (x *ListFederatedPodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFederatedPodsResponse.ProtoReflect.Descriptor instead.
func (*ListFederatedPodsResponse) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{8}
}

func (x *ListFederatedPodsResponse) GetResults() []*FederatedPods {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_federation_proto protoreflect.FileDescriptor

const file_federation_proto_rawDesc = "" +
	"\n" +
	"\x10federation.proto\x12\rnimbuscore.v1\x1a\tpod.proto\">\n" +
	"\rRemoteCluster\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bapi_addr\x18\x02 \x01(\tR\aapiAddr\"f\n" +
	"\x16RegisterClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bapi_addr\x18\x02 \x01(\tR\aapiAddr\x12\x1d\n" +
	"\n" +
	"join_token\x18\x03 \x01(\tR\tjoinToken\".\n" +
	"\x18UnregisterClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1b\n" +
	"\x19UnregisterClusterResponse\"\x15\n" +
	"\x13ListClustersRequest\"J\n" +
	"\x14ListClustersResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.nimbuscore.v1.RemoteClusterR\x05items\"8\n" +
	"\x18ListFederatedPodsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"i\n" +
	"\rFederatedPods\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.nimbuscore.v1.PodR\x05items\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"S\n" +
	"\x19ListFederatedPodsResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.nimbuscore.v1.FederatedPodsR\aresults2\x94\x03\n" +
	"\x11FederationService\x12V\n" +
	"\x0fRegisterCluster\x12%.nimbuscore.v1.RegisterClusterRequest\x1a\x1c.nimbuscore.v1.RemoteCluster\x12f\n" +
	"\x11UnregisterCluster\x12'.nimbuscore.v1.UnregisterClusterRequest\x1a(.nimbuscore.v1.UnregisterClusterResponse\x12W\n" +
	"\fListClusters\x12\".nimbuscore.v1.ListClustersRequest\x1a#.nimbuscore.v1.ListClustersResponse\x12f\n" +
	"\x11ListFederatedPods\x12'.nimbuscore.v1.ListFederatedPodsRequest\x1a(.nimbuscore.v1.ListFederatedPodsResponseB/Z-github.com/gh0st-nemesis/nimbuscore/api/v1;v1b\x06proto3"

var (
	file_federation_proto_rawDescOnce sync.Once
	file_federation_proto_rawDescData []byte
)

func file_federation_proto_rawDescGZIP() []byte {
	file_federation_proto_rawDescOnce.Do(func() {
		file_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_federation_proto_rawDesc), len(file_federation_proto_rawDesc)))
	})
	return file_federation_proto_rawDescData
}

var file_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_federation_proto_goTypes = []any{
	(*RemoteCluster)(nil),             // 0: nimbuscore.v1.RemoteCluster
	(*RegisterClusterRequest)(nil),    // 1: nimbuscore.v1.RegisterClusterRequest
	(*UnregisterClusterRequest)(nil),  // 2: nimbuscore.v1.UnregisterClusterRequest
	(*UnregisterClusterResponse)(nil), // 3: nimbuscore.v1.UnregisterClusterResponse
	(*ListClustersRequest)(nil),       // 4: nimbuscore.v1.ListClustersRequest
	(*ListClustersResponse)(nil),      // 5: nimbuscore.v1.ListClustersResponse
	(*ListFederatedPodsRequest)(nil),  // 6: nimbuscore.v1.ListFederatedPodsRequest
	(*FederatedPods)(nil),             // 7: nimbuscore.v1.FederatedPods
	(*ListFederatedPodsResponse)(nil), // 8: nimbuscore.v1.ListFederatedPodsResponse
	(*Pod)(nil),                       // 9: nimbuscore.v1.Pod
}
var file_federation_proto_depIdxs = []int32{
	0, // 0: nimbuscore.v1.ListClustersResponse.items:type_name -> nimbuscore.v1.RemoteCluster
	9, // 1: nimbuscore.v1.FederatedPods.items:type_name -> nimbuscore.v1.Pod
	7, // 2: nimbuscore.v1.ListFederatedPodsResponse.results:type_name -> nimbuscore.v1.FederatedPods
	1, // 3: nimbuscore.v1.FederationService.RegisterCluster:input_type -> nimbuscore.v1.RegisterClusterRequest
	2, // 4: nimbuscore.v1.FederationService.UnregisterCluster:input_type -> nimbuscore.v1.UnregisterClusterRequest
	4, // 5: nimbuscore.v1.FederationService.ListClusters:input_type -> nimbuscore.v1.ListClustersRequest
	6, // 6: nimbuscore.v1.FederationService.ListFederatedPods:input_type -> nimbuscore.v1.ListFederatedPodsRequest
	0, // 7: nimbuscore.v1.FederationService.RegisterCluster:output_type -> nimbuscore.v1.RemoteCluster
	3, // 8: nimbuscore.v1.FederationService.UnregisterCluster:output_type -> nimbuscore.v1.UnregisterClusterResponse
	5, // 9: nimbuscore.v1.FederationService.ListClusters:output_type -> nimbuscore.v1.ListClustersResponse
	8, // 10: nimbuscore.v1.FederationService.ListFederatedPods:output_type -> nimbuscore.v1.ListFederatedPodsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_federation_proto_init() }
func file_federation_proto_init() {
	if File_federation_proto != nil {
		return
	}
	file_pod_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_federation_proto_rawDesc), len(file_federation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_federation_proto_goTypes,
		DependencyIndexes: file_federation_proto_depIdxs,
		MessageInfos:      file_federation_proto_msgTypes,
	}.Build()
	File_federation_proto = out.File
	file_federation_proto_goTypes = nil
	file_federation_proto_depIdxs = nil
}
