// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: finops.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CostReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	LabelKey      string                 `protobuf:"bytes,2,opt,name=label_key,json=labelKey,proto3" json:"label_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostReportRequest) Reset() {
	*x = CostReportRequest{}
	mi := &file_finops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostReportRequest) ProtoMessage() {}

func (x *CostReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostReportRequest.ProtoReflect.Descriptor instead.
func (*CostReportRequest) Descriptor() ([]byte, []int) {
	return file_finops_proto_rawDescGZIP(), []int{0}
}

func (x *CostReportRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CostReportRequest) GetLabelKey() string {
	if x != nil {
		return x.LabelKey
	}
	return ""
}

type CostReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         float64                `protobuf:"fixed64,1,opt,name=total,proto3" json:"total,omitempty"`
	ByNamespace   map[string]float64     `protobuf:"bytes,2,rep,name=by_namespace,json=byNamespace,proto3" json:"by_namespace,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	ByLabel       map[string]float64     `protobuf:"bytes,3,rep,name=by_label,json=byLabel,proto3" json:"by_label,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostReport) Reset() {
	*x = CostReport{}
	mi := &file_finops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostReport) ProtoMessage() {}

func (x *CostReport) ProtoReflect() protoreflect.Message {
	mi := &file_finops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostReport.ProtoReflect.Descriptor instead.
func (*CostReport) Descriptor() ([]byte, []int) {
	return file_finops_proto_rawDescGZIP(), []int{1}
}

func (x *CostReport) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CostReport) GetByNamespace() map[string]float64 {
	if x != nil {
		return x.ByNamespace
	}
	return nil
}

func (x *CostReport) GetByLabel() map[string]float64 {
	if x != nil {
		return x.ByLabel
	}
	return nil
}

var File_finops_proto protoreflect.FileDescriptor

const file_finops_proto_rawDesc = "" +
	"\n" +
	"\ffinops.proto\x12\rnimbuscore.v1\"N\n" +
	"\x11CostReportRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tlabel_key\x18\x02 \x01(\tR\blabelKey\"\xb0\x02\n" +
	"\n" +
	"CostReport\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x01R\x05total\x12M\n" +
	"\fby_namespace\x18\x02 \x03(\v2*.nimbuscore.v1.CostReport.ByNamespaceEntryR\vbyNamespace\x12A\n" +
	"\bby_label\x18\x03 \x03(\v2&.nimbuscore.v1.CostReport.ByLabelEntryR\abyLabel\x1a>\n" +
	"\x10ByNamespaceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a:\n" +
	"\fByLabelEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x012]\n" +
	"\rFinOpsService\x12L\n" +
	"\rGetCostReport\x12 .nimbuscore.v1.CostReportRequest\x1a\x19.nimbuscore.v1.CostReportB/Z-github.com/gh0st-nemesis/nimbuscore/api/v1;v1b\x06proto3"

var (
	file_finops_proto_rawDescOnce sync.Once
	file_finops_proto_rawDescData []byte
)

func file_finops_proto_rawDescGZIP() []byte {
	file_finops_proto_rawDescOnce.Do(func() {
		file_finops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finops_proto_rawDesc), len(file_finops_proto_rawDesc)))
	})
	return file_finops_proto_rawDescData
}

var file_finops_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_finops_proto_goTypes = []any{
	(*CostReportRequest)(nil), // 0: nimbuscore.v1.CostReportRequest
	(*CostReport)(nil),        // 1: nimbuscore.v1.CostReport
	nil,                       // 2: nimbuscore.v1.CostReport.ByNamespaceEntry
	nil,                       // 3: nimbuscore.v1.CostReport.ByLabelEntry
}
var file_finops_proto_depIdxs = []int32{
	2, // 0: nimbuscore.v1.CostReport.by_namespace:type_name -> nimbuscore.v1.CostReport.ByNamespaceEntry
	3, // 1: nimbuscore.v1.CostReport.by_label:type_name -> nimbuscore.v1.CostReport.ByLabelEntry
	0, // 2: nimbuscore.v1.FinOpsService.GetCostReport:input_type -> nimbuscore.v1.CostReportRequest
	1, // 3: nimbuscore.v1.FinOpsService.GetCostReport:output_type -> nimbuscore.v1.CostReport
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_finops_proto_init() }
func file_finops_proto_init() {
	if File_finops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finops_proto_rawDesc), len(file_finops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finops_proto_goTypes,
		DependencyIndexes: file_finops_proto_depIdxs,
		MessageInfos:      file_finops_proto_msgTypes,
	}.Build()
	File_finops_proto = out.File
	file_finops_proto_goTypes = nil
	file_finops_proto_depIdxs = nil
}
