// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: finops.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FinOpsService_GetCostReport_FullMethodName = "/nimbuscore.v1.FinOpsService/GetCostReport"
)

// FinOpsServiceClient is the client API for FinOpsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinOpsServiceClient interface {
	GetCostReport(ctx context.Context, in *CostReportRequest, opts ...grpc.CallOption) (*CostReport, error)
}

type finOpsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFinOpsServiceClient(cc grpc.ClientConnInterface) FinOpsServiceClient {
	return &finOpsServiceClient{cc}
}

func (c *finOpsServiceClient) GetCostReport(ctx context.Context, in *CostReportRequest, opts ...grpc.CallOption) (*CostReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CostReport)
	err := c.cc.Invoke(ctx, FinOpsService_GetCostReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinOpsServiceServer is the server API for FinOpsService service.
// All implementations must embed UnimplementedFinOpsServiceServer
// for forward compatibility.
type FinOpsServiceServer interface {
	GetCostReport(context.Context, *CostReportRequest) (*CostReport, error)
	mustEmbedUnimplementedFinOpsServiceServer()
}

// UnimplementedFinOpsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFinOpsServiceServer struct{}

func (UnimplementedFinOpsServiceServer) GetCostReport(context.Context, *CostReportRequest) (*CostReport, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCostReport not implemented")
}
func (UnimplementedFinOpsServiceServer) mustEmbedUnimplementedFinOpsServiceServer() {}
func (UnimplementedFinOpsServiceServer) testEmbeddedByValue()                       {}

// UnsafeFinOpsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinOpsServiceServer will
// result in compilation errors.
type UnsafeFinOpsServiceServer interface {
	mustEmbedUnimplementedFinOpsServiceServer()
}

func RegisterFinOpsServiceServer(s grpc.ServiceRegistrar, srv FinOpsServiceServer) {
	// If the following call panics, it indicates UnimplementedFinOpsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FinOpsService_ServiceDesc, srv)
}

func _FinOpsService_GetCostReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CostReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinOpsServiceServer).GetCostReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinOpsService_GetCostReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinOpsServiceServer).GetCostReport(ctx, req.(*CostReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FinOpsService_ServiceDesc is the grpc.ServiceDesc for FinOpsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinOpsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nimbuscore.v1.FinOpsService",
	HandlerType: (*FinOpsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCostReport",
			Handler:    _FinOpsService_GetCostReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finops.proto",
}
