// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: imageregistry.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	PushedAtUnix  int64                  `protobuf:"varint,3,opt,name=pushed_at_unix,json=pushedAtUnix,proto3" json:"pushed_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRecord) Reset() {
	*x = ImageRecord{}
	mi := &file_imageregistry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRecord) ProtoMessage() {}

func (x *ImageRecord) ProtoReflect() protoreflect.Message {
	mi := &file_imageregistry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRecord.ProtoReflect.Descriptor instead.
func (*ImageRecord) Descriptor() ([]byte, []int) {
	return file_imageregistry_proto_rawDescGZIP(), []int{0}
}

func (x *ImageRecord) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *ImageRecord) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ImageRecord) GetPushedAtUnix() int64 {
	if x != nil {
		return x.PushedAtUnix
	}
	return 0
}

type PushImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushImageRequest) Reset() {
	*x = PushImageRequest{}
	mi := &file_imageregistry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushImageRequest) ProtoMessage() {}

func (x *PushImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_imageregistry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushImageRequest.ProtoReflect.Descriptor instead.
func (*PushImageRequest) Descriptor() ([]byte, []int) {
	return file_imageregistry_proto_rawDescGZIP(), []int{1}
}

func (x *PushImageRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *PushImageRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type GetImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageRequest) Reset() {
	*x = GetImageRequest{}
	mi := &file_imageregistry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageRequest) ProtoMessage() {}

func (x *GetImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_imageregistry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageRequest.ProtoReflect.Descriptor instead.
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return file_imageregistry_proto_rawDescGZIP(), []int{2}
}

func (x *GetImageRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type ListImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_imageregistry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_imageregistry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_imageregistry_proto_rawDescGZIP(), []int{3}
}

type ListImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ImageRecord         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_imageregistry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_imageregistry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_imageregistry_proto_rawDescGZIP(), []int{4}
}

func (x *ListImagesResponse) GetItems() []*ImageRecord {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImageRequest) Reset() {
	*x = DeleteImageRequest{}
	mi := &file_imageregistry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImageRequest) ProtoMessage() {}

func (x *DeleteImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_imageregistry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImageRequest.ProtoReflect.Descriptor instead.
func (*DeleteImageRequest) Descriptor() ([]byte, []int) {
	return file_imageregistry_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteImageRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type DeleteImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImageResponse) Reset() {
	*x = DeleteImageResponse{}
	mi := &file_imageregistry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImageResponse) ProtoMessage() {}

func (x *DeleteImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_imageregistry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImageResponse.ProtoReflect.Descriptor instead.
func (*DeleteImageResponse) Descriptor() ([]byte, []int) {
	return file_imageregistry_proto_rawDescGZIP(), []int{6}
}

var File_imageregistry_proto protoreflect.FileDescriptor

const file_imageregistry_proto_rawDesc = "" +
	"\n" +
	"\x13imageregistry.proto\x12\rnimbuscore.v1\"o\n" +
	"\vImageRecord\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12$\n" +
	"\x0epushed_at_unix\x18\x03 \x01(\x03R\fpushedAtUnix\"N\n" +
	"\x10PushImageRequest\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"/\n" +
	"\x0fGetImageRequest\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\"\x13\n" +
	"\x11ListImagesRequest\"F\n" +
	"\x12ListImagesResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.nimbuscore.v1.ImageRecordR\x05items\"2\n" +
	"\x12DeleteImageRequest\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\"\x15\n" +
	"\x13DeleteImageResponse2\xd1\x02\n" +
	"\x14ImageRegistryService\x12H\n" +
	"\tPushImage\x12\x1f.nimbuscore.v1.PushImageRequest\x1a\x1a.nimbuscore.v1.ImageRecord\x12F\n" +
	"\bGetImage\x12\x1e.nimbuscore.v1.GetImageRequest\x1a\x1a.nimbuscore.v1.ImageRecord\x12Q\n" +
	"\n" +
	"ListImages\x12 .nimbuscore.v1.ListImagesRequest\x1a!.nimbuscore.v1.ListImagesResponse\x12T\n" +
	"\vDeleteImage\x12!.nimbuscore.v1.DeleteImageRequest\x1a\".nimbuscore.v1.DeleteImageResponseB/Z-github.com/gh0st-nemesis/nimbuscore/api/v1;v1b\x06proto3"

var (
	file_imageregistry_proto_rawDescOnce sync.Once
	file_imageregistry_proto_rawDescData []byte
)

func file_imageregistry_proto_rawDescGZIP() []byte {
	file_imageregistry_proto_rawDescOnce.Do(func() {
		file_imageregistry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_imageregistry_proto_rawDesc), len(file_imageregistry_proto_rawDesc)))
	})
	return file_imageregistry_proto_rawDescData
}

var file_imageregistry_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_imageregistry_proto_goTypes = []any{
	(*ImageRecord)(nil),         // 0: nimbuscore.v1.ImageRecord
	(*PushImageRequest)(nil),    // 1: nimbuscore.v1.PushImageRequest
	(*GetImageRequest)(nil),     // 2: nimbuscore.v1.GetImageRequest
	(*ListImagesRequest)(nil),   // 3: nimbuscore.v1.ListImagesRequest
	(*ListImagesResponse)(nil),  // 4: nimbuscore.v1.ListImagesResponse
	(*DeleteImageRequest)(nil),  // 5: nimbuscore.v1.DeleteImageRequest
	(*DeleteImageResponse)(nil), // 6: nimbuscore.v1.DeleteImageResponse
}
var file_imageregistry_proto_depIdxs = []int32{
	0, // 0: nimbuscore.v1.ListImagesResponse.items:type_name -> nimbuscore.v1.ImageRecord
	1, // 1: nimbuscore.v1.ImageRegistryService.PushImage:input_type -> nimbuscore.v1.PushImageRequest
	2, // 2: nimbuscore.v1.ImageRegistryService.GetImage:input_type -> nimbuscore.v1.GetImageRequest
	3, // 3: nimbuscore.v1.ImageRegistryService.ListImages:input_type -> nimbuscore.v1.ListImagesRequest
	5, // 4: nimbuscore.v1.ImageRegistryService.DeleteImage:input_type -> nimbuscore.v1.DeleteImageRequest
	0, // 5: nimbuscore.v1.ImageRegistryService.PushImage:output_type -> nimbuscore.v1.ImageRecord
	0, // 6: nimbuscore.v1.ImageRegistryService.GetImage:output_type -> nimbuscore.v1.ImageRecord
	4, // 7: nimbuscore.v1.ImageRegistryService.ListImages:output_type -> nimbuscore.v1.ListImagesResponse
	6, // 8: nimbuscore.v1.ImageRegistryService.DeleteImage:output_type -> nimbuscore.v1.DeleteImageResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_imageregistry_proto_init() }
func file_imageregistry_proto_init() {
	if File_imageregistry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_imageregistry_proto_rawDesc), len(file_imageregistry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_imageregistry_proto_goTypes,
		DependencyIndexes: file_imageregistry_proto_depIdxs,
		MessageInfos:      file_imageregistry_proto_msgTypes,
	}.Build()
	File_imageregistry_proto = out.File
	file_imageregistry_proto_goTypes = nil
	file_imageregistry_proto_depIdxs = nil
}
