// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: imageregistry.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImageRegistryService_PushImage_FullMethodName   = "/nimbuscore.v1.ImageRegistryService/PushImage"
	ImageRegistryService_GetImage_FullMethodName    = "/nimbuscore.v1.ImageRegistryService/GetImage"
	ImageRegistryService_ListImages_FullMethodName  = "/nimbuscore.v1.ImageRegistryService/ListImages"
	ImageRegistryService_DeleteImage_FullMethodName = "/nimbuscore.v1.ImageRegistryService/DeleteImage"
)

// ImageRegistryServiceClient is the client API for ImageRegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageRegistryServiceClient interface {
	PushImage(ctx context.Context, in *PushImageRequest, opts ...grpc.CallOption) (*ImageRecord, error)
	GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*ImageRecord, error)
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*DeleteImageResponse, error)
}

type imageRegistryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageRegistryServiceClient(cc grpc.ClientConnInterface) ImageRegistryServiceClient {
	return &imageRegistryServiceClient{cc}
}

func (c *imageRegistryServiceClient) PushImage(ctx context.Context, in *PushImageRequest, opts ...grpc.CallOption) (*ImageRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageRecord)
	err := c.cc.Invoke(ctx, ImageRegistryService_PushImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageRegistryServiceClient) GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*ImageRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageRecord)
	err := c.cc.Invoke(ctx, ImageRegistryService_GetImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageRegistryServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, ImageRegistryService_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageRegistryServiceClient) DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*DeleteImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteImageResponse)
	err := c.cc.Invoke(ctx, ImageRegistryService_DeleteImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageRegistryServiceServer is the server API for ImageRegistryService service.
// All implementations must embed UnimplementedImageRegistryServiceServer
// for forward compatibility.
type ImageRegistryServiceServer interface {
	PushImage(context.Context, *PushImageRequest) (*ImageRecord, error)
	GetImage(context.Context, *GetImageRequest) (*ImageRecord, error)
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	DeleteImage(context.Context, *DeleteImageRequest) (*DeleteImageResponse, error)
	mustEmbedUnimplementedImageRegistryServiceServer()
}

// UnimplementedImageRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageRegistryServiceServer struct{}

func (UnimplementedImageRegistryServiceServer) PushImage(context.Context, *PushImageRequest) (*ImageRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method PushImage not implemented")
}
func (UnimplementedImageRegistryServiceServer) GetImage(context.Context, *GetImageRequest) (*ImageRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method GetImage not implemented")
}
func (UnimplementedImageRegistryServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedImageRegistryServiceServer) DeleteImage(context.Context, *DeleteImageRequest) (*DeleteImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteImage not implemented")
}
func (UnimplementedImageRegistryServiceServer) mustEmbedUnimplementedImageRegistryServiceServer() {}
func (UnimplementedImageRegistryServiceServer) testEmbeddedByValue()                              {}

// UnsafeImageRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageRegistryServiceServer will
// result in compilation errors.
type UnsafeImageRegistryServiceServer interface {
	mustEmbedUnimplementedImageRegistryServiceServer()
}

func RegisterImageRegistryServiceServer(s grpc.ServiceRegistrar, srv ImageRegistryServiceServer) {
	// If the following call panics, it indicates UnimplementedImageRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageRegistryService_ServiceDesc, srv)
}

func _ImageRegistryService_PushImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageRegistryServiceServer).PushImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageRegistryService_PushImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageRegistryServiceServer).PushImage(ctx, req.(*PushImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageRegistryService_GetImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageRegistryServiceServer).GetImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageRegistryService_GetImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageRegistryServiceServer).GetImage(ctx, req.(*GetImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageRegistryService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageRegistryServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageRegistryService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageRegistryServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageRegistryService_DeleteImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageRegistryServiceServer).DeleteImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageRegistryService_DeleteImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageRegistryServiceServer).DeleteImage(ctx, req.(*DeleteImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageRegistryService_ServiceDesc is the grpc.ServiceDesc for ImageRegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageRegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nimbuscore.v1.ImageRegistryService",
	HandlerType: (*ImageRegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushImage",
			Handler:    _ImageRegistryService_PushImage_Handler,
		},
		{
			MethodName: "GetImage",
			Handler:    _ImageRegistryService_GetImage_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _ImageRegistryService_ListImages_Handler,
		},
		{
			MethodName: "DeleteImage",
			Handler:    _ImageRegistryService_DeleteImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "imageregistry.proto",
}
