// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: networkpolicy.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkPolicyPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyPort) Reset() {
	*x = NetworkPolicyPort{}
	mi := &file_networkpolicy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyPort) ProtoMessage() {}

func (x *NetworkPolicyPort) ProtoReflect() protoreflect.Message {
	mi := &file_networkpolicy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyPort.ProtoReflect.Descriptor instead.
func (*NetworkPolicyPort) Descriptor() ([]byte, []int) {
	return file_networkpolicy_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkPolicyPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkPolicyPort) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type NetworkPolicyPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodSelector   map[string]string      `protobuf:"bytes,1,rep,name=pod_selector,json=podSelector,proto3" json:"pod_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyPeer) Reset() {
	*x = NetworkPolicyPeer{}
	mi := &file_networkpolicy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyPeer) ProtoMessage() {}

func (x *NetworkPolicyPeer) ProtoReflect() protoreflect.Message {
	mi := &file_networkpolicy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyPeer.ProtoReflect.Descriptor instead.
func (*NetworkPolicyPeer) Descriptor() ([]byte, []int) {
	return file_networkpolicy_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkPolicyPeer) GetPodSelector() map[string]string {
	if x != nil {
		return x.PodSelector
	}
	return nil
}

type NetworkPolicyIngressRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          []*NetworkPolicyPeer   `protobuf:"bytes,1,rep,name=from,proto3" json:"from,omitempty"`
	Ports         []*NetworkPolicyPort   `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyIngressRule) Reset() {
	*x = NetworkPolicyIngressRule{}
	mi := &file_networkpolicy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyIngressRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyIngressRule) ProtoMessage() {}

func (x *NetworkPolicyIngressRule) ProtoReflect() protoreflect.Message {
	mi := &file_networkpolicy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyIngressRule.ProtoReflect.Descriptor instead.
func (*NetworkPolicyIngressRule) Descriptor() ([]byte, []int) {
	return file_networkpolicy_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkPolicyIngressRule) GetFrom() []*NetworkPolicyPeer {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *NetworkPolicyIngressRule) GetPorts() []*NetworkPolicyPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

type NetworkPolicySpec struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	PodSelector   map[string]string           `protobuf:"bytes,1,rep,name=pod_selector,json=podSelector,proto3" json:"pod_selector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ingress       []*NetworkPolicyIngressRule `protobuf:"bytes,2,rep,name=ingress,proto3" json:"ingress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicySpec) Reset() {
	*x = NetworkPolicySpec{}
	mi := &file_networkpolicy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicySpec) ProtoMessage() {}

func (x *NetworkPolicySpec) ProtoReflect() protoreflect.Message {
	mi := &file_networkpolicy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicySpec.ProtoReflect.Descriptor instead.
func (*NetworkPolicySpec) Descriptor() ([]byte, []int) {
	return file_networkpolicy_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkPolicySpec) GetPodSelector() map[string]string {
	if x != nil {
		return x.PodSelector
	}
	return nil
}

func (x *NetworkPolicySpec) GetIngress() []*NetworkPolicyIngressRule {
	if x != nil {
		return x.Ingress
	}
	return nil
}

type NetworkPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ObjectMeta            `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *NetworkPolicySpec     `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicy) Reset() {
	*x = NetworkPolicy{}
	mi := &file_networkpolicy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicy) ProtoMessage() {}

func (x *NetworkPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_networkpolicy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicy.ProtoReflect.Descriptor instead.
func (*NetworkPolicy) Descriptor() ([]byte, []int) {
	return file_networkpolicy_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkPolicy) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NetworkPolicy) GetSpec() *NetworkPolicySpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateNetworkPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetworkPolicy *NetworkPolicy         `protobuf:"bytes,1,opt,name=network_policy,json=networkPolicy,proto3" json:"network_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetworkPolicyRequest) Reset() {
	*x = CreateNetworkPolicyRequest{}
	mi := &file_networkpolicy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetworkPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkPolicyRequest) ProtoMessage() {}

func (x *CreateNetworkPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networkpolicy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkPolicyRequest.ProtoReflect.Descriptor instead.
func (*CreateNetworkPolicyRequest) Descriptor() ([]byte, []int) {
	return file_networkpolicy_proto_rawDescGZIP(), []int{5}
}

func (x *CreateNetworkPolicyRequest) GetNetworkPolicy() *NetworkPolicy {
	if x != nil {
		return x.NetworkPolicy
	}
	return nil
}

type GetNetworkPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkPolicyRequest) Reset() {
	*x = GetNetworkPolicyRequest{}
	mi := &file_networkpolicy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkPolicyRequest) ProtoMessage() {}

func (x *GetNetworkPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networkpolicy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkPolicyRequest) Descriptor() ([]byte, []int) {
	return file_networkpolicy_proto_rawDescGZIP(), []int{6}
}

func (x *GetNetworkPolicyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetNetworkPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListNetworkPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkPoliciesRequest) Reset() {
	*x = ListNetworkPoliciesRequest{}
	mi := &file_networkpolicy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkPoliciesRequest) ProtoMessage() {}

func (x *ListNetworkPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networkpolicy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListNetworkPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_networkpolicy_proto_rawDescGZIP(), []int{7}
}

func (x *ListNetworkPoliciesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListNetworkPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*NetworkPolicy       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNetworkPoliciesResponse) Reset() {
	*x = ListNetworkPoliciesResponse{}
	mi := &file_networkpolicy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNetworkPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNetworkPoliciesResponse) ProtoMessage() {}

func (x *ListNetworkPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networkpolicy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNetworkPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListNetworkPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_networkpolicy_proto_rawDescGZIP(), []int{8}
}

func (x *ListNetworkPoliciesResponse) GetItems() []*NetworkPolicy {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteNetworkPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkPolicyRequest) Reset() {
	*x = DeleteNetworkPolicyRequest{}
	mi := &file_networkpolicy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkPolicyRequest) ProtoMessage() {}

func (x *DeleteNetworkPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_networkpolicy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkPolicyRequest.ProtoReflect.Descriptor instead.
func (*DeleteNetworkPolicyRequest) Descriptor() ([]byte, []int) {
	return file_networkpolicy_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteNetworkPolicyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteNetworkPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteNetworkPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkPolicyResponse) Reset() {
	*x = DeleteNetworkPolicyResponse{}
	mi := &file_networkpolicy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkPolicyResponse) ProtoMessage() {}

func (x *DeleteNetworkPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_networkpolicy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkPolicyResponse.ProtoReflect.Descriptor instead.
func (*DeleteNetworkPolicyResponse) Descriptor() ([]byte, []int) {
	return file_networkpolicy_proto_rawDescGZIP(), []int{10}
}

var File_networkpolicy_proto protoreflect.FileDescriptor

const file_networkpolicy_proto_rawDesc = "" +
	"\n" +
	"\x13networkpolicy.proto\x12\rnimbuscore.v1\x1a\fcommon.proto\"C\n" +
	"\x11NetworkPolicyPort\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"\xa9\x01\n" +
	"\x11NetworkPolicyPeer\x12T\n" +
	"\fpod_selector\x18\x01 \x03(\v21.nimbuscore.v1.NetworkPolicyPeer.PodSelectorEntryR\vpodSelector\x1a>\n" +
	"\x10PodSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x01\n" +
	"\x18NetworkPolicyIngressRule\x124\n" +
	"\x04from\x18\x01 \x03(\v2 .nimbuscore.v1.NetworkPolicyPeerR\x04from\x126\n" +
	"\x05ports\x18\x02 \x03(\v2 .nimbuscore.v1.NetworkPolicyPortR\x05ports\"\xec\x01\n" +
	"\x11NetworkPolicySpec\x12T\n" +
	"\fpod_selector\x18\x01 \x03(\v21.nimbuscore.v1.NetworkPolicySpec.PodSelectorEntryR\vpodSelector\x12A\n" +
	"\aingress\x18\x02 \x03(\v2'.nimbuscore.v1.NetworkPolicyIngressRuleR\aingress\x1a>\n" +
	"\x10PodSelectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\rNetworkPolicy\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.nimbuscore.v1.ObjectMetaR\bmetadata\x124\n" +
	"\x04spec\x18\x02 \x01(\v2 .nimbuscore.v1.NetworkPolicySpecR\x04spec\"a\n" +
	"\x1aCreateNetworkPolicyRequest\x12C\n" +
	"\x0enetwork_policy\x18\x01 \x01(\v2\x1c.nimbuscore.v1.NetworkPolicyR\rnetworkPolicy\"K\n" +
	"\x17GetNetworkPolicyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\":\n" +
	"\x1aListNetworkPoliciesRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"Q\n" +
	"\x1bListNetworkPoliciesResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.nimbuscore.v1.NetworkPolicyR\x05items\"N\n" +
	"\x1aDeleteNetworkPolicyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x1d\n" +
	"\x1bDeleteNetworkPolicyResponse2\xac\x03\n" +
	"\x14NetworkPolicyService\x12^\n" +
	"\x13CreateNetworkPolicy\x12).nimbuscore.v1.CreateNetworkPolicyRequest\x1a\x1c.nimbuscore.v1.NetworkPolicy\x12X\n" +
	"\x10GetNetworkPolicy\x12&.nimbuscore.v1.GetNetworkPolicyRequest\x1a\x1c.nimbuscore.v1.NetworkPolicy\x12l\n" +
	"\x13ListNetworkPolicies\x12).nimbuscore.v1.ListNetworkPoliciesRequest\x1a*.nimbuscore.v1.ListNetworkPoliciesResponse\x12l\n" +
	"\x13DeleteNetworkPolicy\x12).nimbuscore.v1.DeleteNetworkPolicyRequest\x1a*.nimbuscore.v1.DeleteNetworkPolicyResponseB/Z-github.com/gh0st-nemesis/nimbuscore/api/v1;v1b\x06proto3"

var (
	file_networkpolicy_proto_rawDescOnce sync.Once
	file_networkpolicy_proto_rawDescData []byte
)

func file_networkpolicy_proto_rawDescGZIP() []byte {
	file_networkpolicy_proto_rawDescOnce.Do(func() {
		file_networkpolicy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_networkpolicy_proto_rawDesc), len(file_networkpolicy_proto_rawDesc)))
	})
	return file_networkpolicy_proto_rawDescData
}

var file_networkpolicy_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_networkpolicy_proto_goTypes = []any{
	(*NetworkPolicyPort)(nil),           // 0: nimbuscore.v1.NetworkPolicyPort
	(*NetworkPolicyPeer)(nil),           // 1: nimbuscore.v1.NetworkPolicyPeer
	(*NetworkPolicyIngressRule)(nil),    // 2: nimbuscore.v1.NetworkPolicyIngressRule
	(*NetworkPolicySpec)(nil),           // 3: nimbuscore.v1.NetworkPolicySpec
	(*NetworkPolicy)(nil),               // 4: nimbuscore.v1.NetworkPolicy
	(*CreateNetworkPolicyRequest)(nil),  // 5: nimbuscore.v1.CreateNetworkPolicyRequest
	(*GetNetworkPolicyRequest)(nil),     // 6: nimbuscore.v1.GetNetworkPolicyRequest
	(*ListNetworkPoliciesRequest)(nil),  // 7: nimbuscore.v1.ListNetworkPoliciesRequest
	(*ListNetworkPoliciesResponse)(nil), // 8: nimbuscore.v1.ListNetworkPoliciesResponse
	(*DeleteNetworkPolicyRequest)(nil),  // 9: nimbuscore.v1.DeleteNetworkPolicyRequest
	(*DeleteNetworkPolicyResponse)(nil), // 10: nimbuscore.v1.DeleteNetworkPolicyResponse
	nil,                                 // 11: nimbuscore.v1.NetworkPolicyPeer.PodSelectorEntry
	nil,                                 // 12: nimbuscore.v1.NetworkPolicySpec.PodSelectorEntry
	(*ObjectMeta)(nil),                  // 13: nimbuscore.v1.ObjectMeta
}
var file_networkpolicy_proto_depIdxs = []int32{
	11, // 0: nimbuscore.v1.NetworkPolicyPeer.pod_selector:type_name -> nimbuscore.v1.NetworkPolicyPeer.PodSelectorEntry
	1,  // 1: nimbuscore.v1.NetworkPolicyIngressRule.from:type_name -> nimbuscore.v1.NetworkPolicyPeer
	0,  // 2: nimbuscore.v1.NetworkPolicyIngressRule.ports:type_name -> nimbuscore.v1.NetworkPolicyPort
	12, // 3: nimbuscore.v1.NetworkPolicySpec.pod_selector:type_name -> nimbuscore.v1.NetworkPolicySpec.PodSelectorEntry
	2,  // 4: nimbuscore.v1.NetworkPolicySpec.ingress:type_name -> nimbuscore.v1.NetworkPolicyIngressRule
	13, // 5: nimbuscore.v1.NetworkPolicy.metadata:type_name -> nimbuscore.v1.ObjectMeta
	3,  // 6: nimbuscore.v1.NetworkPolicy.spec:type_name -> nimbuscore.v1.NetworkPolicySpec
	4,  // 7: nimbuscore.v1.CreateNetworkPolicyRequest.network_policy:type_name -> nimbuscore.v1.NetworkPolicy
	4,  // 8: nimbuscore.v1.ListNetworkPoliciesResponse.items:type_name -> nimbuscore.v1.NetworkPolicy
	5,  // 9: nimbuscore.v1.NetworkPolicyService.CreateNetworkPolicy:input_type -> nimbuscore.v1.CreateNetworkPolicyRequest
	6,  // 10: nimbuscore.v1.NetworkPolicyService.GetNetworkPolicy:input_type -> nimbuscore.v1.GetNetworkPolicyRequest
	7,  // 11: nimbuscore.v1.NetworkPolicyService.ListNetworkPolicies:input_type -> nimbuscore.v1.ListNetworkPoliciesRequest
	9,  // 12: nimbuscore.v1.NetworkPolicyService.DeleteNetworkPolicy:input_type -> nimbuscore.v1.DeleteNetworkPolicyRequest
	4,  // 13: nimbuscore.v1.NetworkPolicyService.CreateNetworkPolicy:output_type -> nimbuscore.v1.NetworkPolicy
	4,  // 14: nimbuscore.v1.NetworkPolicyService.GetNetworkPolicy:output_type -> nimbuscore.v1.NetworkPolicy
	8,  // 15: nimbuscore.v1.NetworkPolicyService.ListNetworkPolicies:output_type -> nimbuscore.v1.ListNetworkPoliciesResponse
	10, // 16: nimbuscore.v1.NetworkPolicyService.DeleteNetworkPolicy:output_type -> nimbuscore.v1.DeleteNetworkPolicyResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_networkpolicy_proto_init() }
func file_networkpolicy_proto_init() {
	if File_networkpolicy_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_networkpolicy_proto_rawDesc), len(file_networkpolicy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_networkpolicy_proto_goTypes,
		DependencyIndexes: file_networkpolicy_proto_depIdxs,
		MessageInfos:      file_networkpolicy_proto_msgTypes,
	}.Build()
	File_networkpolicy_proto = out.File
	file_networkpolicy_proto_goTypes = nil
	file_networkpolicy_proto_depIdxs = nil
}
