// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: networkpolicy.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkPolicyService_CreateNetworkPolicy_FullMethodName = "/nimbuscore.v1.NetworkPolicyService/CreateNetworkPolicy"
	NetworkPolicyService_GetNetworkPolicy_FullMethodName    = "/nimbuscore.v1.NetworkPolicyService/GetNetworkPolicy"
	NetworkPolicyService_ListNetworkPolicies_FullMethodName = "/nimbuscore.v1.NetworkPolicyService/ListNetworkPolicies"
	NetworkPolicyService_DeleteNetworkPolicy_FullMethodName = "/nimbuscore.v1.NetworkPolicyService/DeleteNetworkPolicy"
)

// NetworkPolicyServiceClient is the client API for NetworkPolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkPolicyServiceClient interface {
	CreateNetworkPolicy(ctx context.Context, in *CreateNetworkPolicyRequest, opts ...grpc.CallOption) (*NetworkPolicy, error)
	GetNetworkPolicy(ctx context.Context, in *GetNetworkPolicyRequest, opts ...grpc.CallOption) (*NetworkPolicy, error)
	ListNetworkPolicies(ctx context.Context, in *ListNetworkPoliciesRequest, opts ...grpc.CallOption) (*ListNetworkPoliciesResponse, error)
	DeleteNetworkPolicy(ctx context.Context, in *DeleteNetworkPolicyRequest, opts ...grpc.CallOption) (*DeleteNetworkPolicyResponse, error)
}

type networkPolicyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkPolicyServiceClient(cc grpc.ClientConnInterface) NetworkPolicyServiceClient {
	return &networkPolicyServiceClient{cc}
}

func (c *networkPolicyServiceClient) CreateNetworkPolicy(ctx context.Context, in *CreateNetworkPolicyRequest, opts ...grpc.CallOption) (*NetworkPolicy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkPolicy)
	err := c.cc.Invoke(ctx, NetworkPolicyService_CreateNetworkPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkPolicyServiceClient) GetNetworkPolicy(ctx context.Context, in *GetNetworkPolicyRequest, opts ...grpc.CallOption) (*NetworkPolicy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkPolicy)
	err := c.cc.Invoke(ctx, NetworkPolicyService_GetNetworkPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkPolicyServiceClient) ListNetworkPolicies(ctx context.Context, in *ListNetworkPoliciesRequest, opts ...grpc.CallOption) (*ListNetworkPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworkPoliciesResponse)
	err := c.cc.Invoke(ctx, NetworkPolicyService_ListNetworkPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkPolicyServiceClient) DeleteNetworkPolicy(ctx context.Context, in *DeleteNetworkPolicyRequest, opts ...grpc.CallOption) (*DeleteNetworkPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNetworkPolicyResponse)
	err := c.cc.Invoke(ctx, NetworkPolicyService_DeleteNetworkPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkPolicyServiceServer is the server API for NetworkPolicyService service.
// All implementations must embed UnimplementedNetworkPolicyServiceServer
// for forward compatibility.
type NetworkPolicyServiceServer interface {
	CreateNetworkPolicy(context.Context, *CreateNetworkPolicyRequest) (*NetworkPolicy, error)
	GetNetworkPolicy(context.Context, *GetNetworkPolicyRequest) (*NetworkPolicy, error)
	ListNetworkPolicies(context.Context, *ListNetworkPoliciesRequest) (*ListNetworkPoliciesResponse, error)
	DeleteNetworkPolicy(context.Context, *DeleteNetworkPolicyRequest) (*DeleteNetworkPolicyResponse, error)
	mustEmbedUnimplementedNetworkPolicyServiceServer()
}

// UnimplementedNetworkPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkPolicyServiceServer struct{}

func (UnimplementedNetworkPolicyServiceServer) CreateNetworkPolicy(context.Context, *CreateNetworkPolicyRequest) (*NetworkPolicy, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNetworkPolicy not implemented")
}
func (UnimplementedNetworkPolicyServiceServer) GetNetworkPolicy(context.Context, *GetNetworkPolicyRequest) (*NetworkPolicy, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkPolicy not implemented")
}
func (UnimplementedNetworkPolicyServiceServer) ListNetworkPolicies(context.Context, *ListNetworkPoliciesRequest) (*ListNetworkPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNetworkPolicies not implemented")
}
func (UnimplementedNetworkPolicyServiceServer) DeleteNetworkPolicy(context.Context, *DeleteNetworkPolicyRequest) (*DeleteNetworkPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNetworkPolicy not implemented")
}
func (UnimplementedNetworkPolicyServiceServer) mustEmbedUnimplementedNetworkPolicyServiceServer() {}
func (UnimplementedNetworkPolicyServiceServer) testEmbeddedByValue()                              {}

// UnsafeNetworkPolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkPolicyServiceServer will
// result in compilation errors.
type UnsafeNetworkPolicyServiceServer interface {
	mustEmbedUnimplementedNetworkPolicyServiceServer()
}

func RegisterNetworkPolicyServiceServer(s grpc.ServiceRegistrar, srv NetworkPolicyServiceServer) {
	// If the following call panics, it indicates UnimplementedNetworkPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkPolicyService_ServiceDesc, srv)
}

func _NetworkPolicyService_CreateNetworkPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetworkPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkPolicyServiceServer).CreateNetworkPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkPolicyService_CreateNetworkPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkPolicyServiceServer).CreateNetworkPolicy(ctx, req.(*CreateNetworkPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkPolicyService_GetNetworkPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkPolicyServiceServer).GetNetworkPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkPolicyService_GetNetworkPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkPolicyServiceServer).GetNetworkPolicy(ctx, req.(*GetNetworkPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkPolicyService_ListNetworkPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworkPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkPolicyServiceServer).ListNetworkPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkPolicyService_ListNetworkPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkPolicyServiceServer).ListNetworkPolicies(ctx, req.(*ListNetworkPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkPolicyService_DeleteNetworkPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNetworkPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkPolicyServiceServer).DeleteNetworkPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkPolicyService_DeleteNetworkPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkPolicyServiceServer).DeleteNetworkPolicy(ctx, req.(*DeleteNetworkPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkPolicyService_ServiceDesc is the grpc.ServiceDesc for NetworkPolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkPolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nimbuscore.v1.NetworkPolicyService",
	HandlerType: (*NetworkPolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNetworkPolicy",
			Handler:    _NetworkPolicyService_CreateNetworkPolicy_Handler,
		},
		{
			MethodName: "GetNetworkPolicy",
			Handler:    _NetworkPolicyService_GetNetworkPolicy_Handler,
		},
		{
			MethodName: "ListNetworkPolicies",
			Handler:    _NetworkPolicyService_ListNetworkPolicies_Handler,
		},
		{
			MethodName: "DeleteNetworkPolicy",
			Handler:    _NetworkPolicyService_DeleteNetworkPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "networkpolicy.proto",
}
