// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: node.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unschedulable bool                   `protobuf:"varint,1,opt,name=unschedulable,proto3" json:"unschedulable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSpec) Reset() {
	*x = NodeSpec{}
	mi := &file_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSpec) ProtoMessage() {}

func (x *NodeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSpec.ProtoReflect.Descriptor instead.
func (*NodeSpec) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeSpec) GetUnschedulable() bool {
	if x != nil {
		return x.Unschedulable
	}
	return false
}

type NodeStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Capacity          *ResourceList          `protobuf:"bytes,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Allocatable       *ResourceList          `protobuf:"bytes,2,opt,name=allocatable,proto3" json:"allocatable,omitempty"`
	Ready             bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	Conditions        []*Condition           `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty"`
	LastHeartbeatUnix int64                  `protobuf:"varint,5,opt,name=last_heartbeat_unix,json=lastHeartbeatUnix,proto3" json:"last_heartbeat_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeStatus) GetCapacity() *ResourceList {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *NodeStatus) GetAllocatable() *ResourceList {
	if x != nil {
		return x.Allocatable
	}
	return nil
}

func (x *NodeStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *NodeStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *NodeStatus) GetLastHeartbeatUnix() int64 {
	if x != nil {
		return x.LastHeartbeatUnix
	}
	return 0
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ObjectMeta            `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *NodeSpec              `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *NodeStatus            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_node_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Node) GetSpec() *NodeSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Node) GetStatus() *NodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_node_proto protoreflect.FileDescriptor

const file_node_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"node.proto\x12\rnimbuscore.v1\x1a\fcommon.proto\"0\n" +
	"\bNodeSpec\x12$\n" +
	"\runschedulable\x18\x01 \x01(\bR\runschedulable\"\x84\x02\n" +
	"\n" +
	"NodeStatus\x127\n" +
	"\bcapacity\x18\x01 \x01(\v2\x1b.nimbuscore.v1.ResourceListR\bcapacity\x12=\n" +
	"\vallocatable\x18\x02 \x01(\v2\x1b.nimbuscore.v1.ResourceListR\vallocatable\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\x128\n" +
	"\n" +
	"conditions\x18\x04 \x03(\v2\x18.nimbuscore.v1.ConditionR\n" +
	"conditions\x12.\n" +
	"\x13last_heartbeat_unix\x18\x05 \x01(\x03R\x11lastHeartbeatUnix\"\x9d\x01\n" +
	"\x04Node\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.nimbuscore.v1.ObjectMetaR\bmetadata\x12+\n" +
	"\x04spec\x18\x02 \x01(\v2\x17.nimbuscore.v1.NodeSpecR\x04spec\x121\n" +
	"\x06status\x18\x03 \x01(\v2\x19.nimbuscore.v1.NodeStatusR\x06statusB/Z-github.com/gh0st-nemesis/nimbuscore/api/v1;v1b\x06proto3"

var (
	file_node_proto_rawDescOnce sync.Once
	file_node_proto_rawDescData []byte
)

func file_node_proto_rawDescGZIP() []byte {
	file_node_proto_rawDescOnce.Do(func() {
		file_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)))
	})
	return file_node_proto_rawDescData
}

var file_node_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_node_proto_goTypes = []any{
	(*NodeSpec)(nil),     // 0: nimbuscore.v1.NodeSpec
	(*NodeStatus)(nil),   // 1: nimbuscore.v1.NodeStatus
	(*Node)(nil),         // 2: nimbuscore.v1.Node
	(*ResourceList)(nil), // 3: nimbuscore.v1.ResourceList
	(*Condition)(nil),    // 4: nimbuscore.v1.Condition
	(*ObjectMeta)(nil),   // 5: nimbuscore.v1.ObjectMeta
}
var file_node_proto_depIdxs = []int32{
	3, // 0: nimbuscore.v1.NodeStatus.capacity:type_name -> nimbuscore.v1.ResourceList
	3, // 1: nimbuscore.v1.NodeStatus.allocatable:type_name -> nimbuscore.v1.ResourceList
	4, // 2: nimbuscore.v1.NodeStatus.conditions:type_name -> nimbuscore.v1.Condition
	5, // 3: nimbuscore.v1.Node.metadata:type_name -> nimbuscore.v1.ObjectMeta
	0, // 4: nimbuscore.v1.Node.spec:type_name -> nimbuscore.v1.NodeSpec
	1, // 5: nimbuscore.v1.Node.status:type_name -> nimbuscore.v1.NodeStatus
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_node_proto_init() }
func file_node_proto_init() {
	if File_node_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_proto_rawDesc), len(file_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_proto_goTypes,
		DependencyIndexes: file_node_proto_depIdxs,
		MessageInfos:      file_node_proto_msgTypes,
	}.Build()
	File_node_proto = out.File
	file_node_proto_goTypes = nil
	file_node_proto_depIdxs = nil
}
