syntax = "proto3";

package nimbuscore.v1;

import "common.proto";

option go_package = "github.com/gh0st-nemesis/nimbuscore/api/v1;v1";

message SecurityContext {
  string seccomp_profile = 1;
  repeated string add_capabilities = 2;
  bool privileged = 3;
  bool allow_privilege_escalation = 4;
  bool run_as_non_root = 5;
}

message Container {
  string name = 1;
  string image = 2;
  ResourceRequirements resources = 3;
  SecurityContext security_context = 4;
}

message PodSpec {
  repeated Container containers = 1;
  string node_name = 2;
}

enum PodPhase {
  POD_PHASE_UNSPECIFIED = 0;
  POD_PHASE_PENDING = 1;
  POD_PHASE_RUNNING = 2;
  POD_PHASE_SUCCEEDED = 3;
  POD_PHASE_FAILED = 4;
  POD_PHASE_UNKNOWN = 5;
}

message PodStatus {
  PodPhase phase = 1;
  string message = 2;
  repeated Condition conditions = 3;
}

message Pod {
  ObjectMeta metadata = 1;
  PodSpec spec = 2;
  PodStatus status = 3;
}
