syntax = "proto3";

package nimbuscore.v1;

import "common.proto";
import "volume.proto";

option go_package = "github.com/gh0st-nemesis/nimbuscore/api/v1;v1";

message SecurityContext {
  string seccomp_profile = 1;
  repeated string add_capabilities = 2;
  bool privileged = 3;
  bool allow_privilege_escalation = 4;
  bool run_as_non_root = 5;
}

message Container {
  string name = 1;
  string image = 2;
  ResourceRequirements resources = 3;
  SecurityContext security_context = 4;
  repeated string command = 5;
  string wasm_module_path = 6;
  repeated int32 container_ports = 7;
  map<string, string> env = 8;
}

enum RestartPolicy {
  RESTART_POLICY_UNSPECIFIED = 0;
  RESTART_POLICY_ALWAYS = 1;
  RESTART_POLICY_ON_FAILURE = 2;
  RESTART_POLICY_NEVER = 3;
}

message PodSpec {
  repeated Container containers = 1;
  string node_name = 2;
  repeated VolumeMount volumes = 3;
  RestartPolicy restart_policy = 4;
}

enum PodPhase {
  POD_PHASE_UNSPECIFIED = 0;
  POD_PHASE_PENDING = 1;
  POD_PHASE_RUNNING = 2;
  POD_PHASE_SUCCEEDED = 3;
  POD_PHASE_FAILED = 4;
  POD_PHASE_UNKNOWN = 5;
}

message PodStatus {
  PodPhase phase = 1;
  string message = 2;
  repeated Condition conditions = 3;
  int32 restart_count = 4;
  int64 memory_usage_bytes = 5;
}

message Pod {
  ObjectMeta metadata = 1;
  PodSpec spec = 2;
  PodStatus status = 3;
}
