// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pod.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestartPolicy int32

const (
	RestartPolicy_RESTART_POLICY_UNSPECIFIED RestartPolicy = 0
	RestartPolicy_RESTART_POLICY_ALWAYS      RestartPolicy = 1
	RestartPolicy_RESTART_POLICY_ON_FAILURE  RestartPolicy = 2
	RestartPolicy_RESTART_POLICY_NEVER       RestartPolicy = 3
)

// Enum value maps for RestartPolicy.
var (
	RestartPolicy_name = map[int32]string{
		0: "RESTART_POLICY_UNSPECIFIED",
		1: "RESTART_POLICY_ALWAYS",
		2: "RESTART_POLICY_ON_FAILURE",
		3: "RESTART_POLICY_NEVER",
	}
	RestartPolicy_value = map[string]int32{
		"RESTART_POLICY_UNSPECIFIED": 0,
		"RESTART_POLICY_ALWAYS":      1,
		"RESTART_POLICY_ON_FAILURE":  2,
		"RESTART_POLICY_NEVER":       3,
	}
)

func (x RestartPolicy) Enum() *RestartPolicy {
	p := new(RestartPolicy)
	*p = x
	return p
}

func (x RestartPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestartPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_pod_proto_enumTypes[0].Descriptor()
}

func (RestartPolicy) Type() protoreflect.EnumType {
	return &file_pod_proto_enumTypes[0]
}

func (x RestartPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestartPolicy.Descriptor instead.
func (RestartPolicy) EnumDescriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{0}
}

type PodPhase int32

const (
	PodPhase_POD_PHASE_UNSPECIFIED PodPhase = 0
	PodPhase_POD_PHASE_PENDING     PodPhase = 1
	PodPhase_POD_PHASE_RUNNING     PodPhase = 2
	PodPhase_POD_PHASE_SUCCEEDED   PodPhase = 3
	PodPhase_POD_PHASE_FAILED      PodPhase = 4
	PodPhase_POD_PHASE_UNKNOWN     PodPhase = 5
)

// Enum value maps for PodPhase.
var (
	PodPhase_name = map[int32]string{
		0: "POD_PHASE_UNSPECIFIED",
		1: "POD_PHASE_PENDING",
		2: "POD_PHASE_RUNNING",
		3: "POD_PHASE_SUCCEEDED",
		4: "POD_PHASE_FAILED",
		5: "POD_PHASE_UNKNOWN",
	}
	PodPhase_value = map[string]int32{
		"POD_PHASE_UNSPECIFIED": 0,
		"POD_PHASE_PENDING":     1,
		"POD_PHASE_RUNNING":     2,
		"POD_PHASE_SUCCEEDED":   3,
		"POD_PHASE_FAILED":      4,
		"POD_PHASE_UNKNOWN":     5,
	}
)

func (x PodPhase) Enum() *PodPhase {
	p := new(PodPhase)
	*p = x
	return p
}

func (x PodPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PodPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_pod_proto_enumTypes[1].Descriptor()
}

func (PodPhase) Type() protoreflect.EnumType {
	return &file_pod_proto_enumTypes[1]
}

func (x PodPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PodPhase.Descriptor instead.
func (PodPhase) EnumDescriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{1}
}

type SecurityContext struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SeccompProfile           string                 `protobuf:"bytes,1,opt,name=seccomp_profile,json=seccompProfile,proto3" json:"seccomp_profile,omitempty"`
	AddCapabilities          []string               `protobuf:"bytes,2,rep,name=add_capabilities,json=addCapabilities,proto3" json:"add_capabilities,omitempty"`
	Privileged               bool                   `protobuf:"varint,3,opt,name=privileged,proto3" json:"privileged,omitempty"`
	AllowPrivilegeEscalation bool                   `protobuf:"varint,4,opt,name=allow_privilege_escalation,json=allowPrivilegeEscalation,proto3" json:"allow_privilege_escalation,omitempty"`
	RunAsNonRoot             bool                   `protobuf:"varint,5,opt,name=run_as_non_root,json=runAsNonRoot,proto3" json:"run_as_non_root,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SecurityContext) Reset() {
	*x = SecurityContext{}
	mi := &file_pod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityContext) ProtoMessage() {}

func (x *SecurityContext) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityContext.ProtoReflect.Descriptor instead.
func (*SecurityContext) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{0}
}

func (x *SecurityContext) GetSeccompProfile() string {
	if x != nil {
		return x.SeccompProfile
	}
	return ""
}

func (x *SecurityContext) GetAddCapabilities() []string {
	if x != nil {
		return x.AddCapabilities
	}
	return nil
}

func (x *SecurityContext) GetPrivileged() bool {
	if x != nil {
		return x.Privileged
	}
	return false
}

func (x *SecurityContext) GetAllowPrivilegeEscalation() bool {
	if x != nil {
		return x.AllowPrivilegeEscalation
	}
	return false
}

func (x *SecurityContext) GetRunAsNonRoot() bool {
	if x != nil {
		return x.RunAsNonRoot
	}
	return false
}

type BuildSource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl        string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	Branch         string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	DockerfilePath string                 `protobuf:"bytes,3,opt,name=dockerfile_path,json=dockerfilePath,proto3" json:"dockerfile_path,omitempty"`
	ContextPath    string                 `protobuf:"bytes,4,opt,name=context_path,json=contextPath,proto3" json:"context_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuildSource) Reset() {
	*x = BuildSource{}
	mi := &file_pod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSource) ProtoMessage() {}

func (x *BuildSource) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSource.ProtoReflect.Descriptor instead.
func (*BuildSource) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{1}
}

func (x *BuildSource) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *BuildSource) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *BuildSource) GetDockerfilePath() string {
	if x != nil {
		return x.DockerfilePath
	}
	return ""
}

func (x *BuildSource) GetContextPath() string {
	if x != nil {
		return x.ContextPath
	}
	return ""
}

type Container struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image           string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Resources       *ResourceRequirements  `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	SecurityContext *SecurityContext       `protobuf:"bytes,4,opt,name=security_context,json=securityContext,proto3" json:"security_context,omitempty"`
	Command         []string               `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	WasmModulePath  string                 `protobuf:"bytes,6,opt,name=wasm_module_path,json=wasmModulePath,proto3" json:"wasm_module_path,omitempty"`
	ContainerPorts  []int32                `protobuf:"varint,7,rep,packed,name=container_ports,json=containerPorts,proto3" json:"container_ports,omitempty"`
	Env             map[string]string      `protobuf:"bytes,8,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BuildSource     *BuildSource           `protobuf:"bytes,9,opt,name=build_source,json=buildSource,proto3" json:"build_source,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_pod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{2}
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetResources() *ResourceRequirements {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Container) GetSecurityContext() *SecurityContext {
	if x != nil {
		return x.SecurityContext
	}
	return nil
}

func (x *Container) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Container) GetWasmModulePath() string {
	if x != nil {
		return x.WasmModulePath
	}
	return ""
}

func (x *Container) GetContainerPorts() []int32 {
	if x != nil {
		return x.ContainerPorts
	}
	return nil
}

func (x *Container) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Container) GetBuildSource() *BuildSource {
	if x != nil {
		return x.BuildSource
	}
	return nil
}

type PodSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Volumes       []*VolumeMount         `protobuf:"bytes,3,rep,name=volumes,proto3" json:"volumes,omitempty"`
	RestartPolicy RestartPolicy          `protobuf:"varint,4,opt,name=restart_policy,json=restartPolicy,proto3,enum=nimbuscore.v1.RestartPolicy" json:"restart_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodSpec) Reset() {
	*x = PodSpec{}
	mi := &file_pod_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodSpec) ProtoMessage() {}

func (x *PodSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodSpec.ProtoReflect.Descriptor instead.
func (*PodSpec) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{3}
}

func (x *PodSpec) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *PodSpec) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PodSpec) GetVolumes() []*VolumeMount {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *PodSpec) GetRestartPolicy() RestartPolicy {
	if x != nil {
		return x.RestartPolicy
	}
	return RestartPolicy_RESTART_POLICY_UNSPECIFIED
}

type PodStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Phase            PodPhase               `protobuf:"varint,1,opt,name=phase,proto3,enum=nimbuscore.v1.PodPhase" json:"phase,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Conditions       []*Condition           `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	RestartCount     int32                  `protobuf:"varint,4,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	MemoryUsageBytes int64                  `protobuf:"varint,5,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PodStatus) Reset() {
	*x = PodStatus{}
	mi := &file_pod_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodStatus) ProtoMessage() {}

func (x *PodStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodStatus.ProtoReflect.Descriptor instead.
func (*PodStatus) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{4}
}

func (x *PodStatus) GetPhase() PodPhase {
	if x != nil {
		return x.Phase
	}
	return PodPhase_POD_PHASE_UNSPECIFIED
}

func (x *PodStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PodStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *PodStatus) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *PodStatus) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

type Pod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ObjectMeta            `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *PodSpec               `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *PodStatus             `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_pod_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_pod_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_pod_proto_rawDescGZIP(), []int{5}
}

func (x *Pod) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Pod) GetSpec() *PodSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Pod) GetStatus() *PodStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_pod_proto protoreflect.FileDescriptor

const file_pod_proto_rawDesc = "" +
	"\n" +
	"\tpod.proto\x12\rnimbuscore.v1\x1a\fcommon.proto\x1a\fvolume.proto\"\xea\x01\n" +
	"\x0fSecurityContext\x12'\n" +
	"\x0fseccomp_profile\x18\x01 \x01(\tR\x0eseccompProfile\x12)\n" +
	"\x10add_capabilities\x18\x02 \x03(\tR\x0faddCapabilities\x12\x1e\n" +
	"\n" +
	"privileged\x18\x03 \x01(\bR\n" +
	"privileged\x12<\n" +
	"\x1aallow_privilege_escalation\x18\x04 \x01(\bR\x18allowPrivilegeEscalation\x12%\n" +
	"\x0frun_as_non_root\x18\x05 \x01(\bR\frunAsNonRoot\"\x8c\x01\n" +
	"\vBuildSource\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12'\n" +
	"\x0fdockerfile_path\x18\x03 \x01(\tR\x0edockerfilePath\x12!\n" +
	"\fcontext_path\x18\x04 \x01(\tR\vcontextPath\"\xdc\x03\n" +
	"\tContainer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12A\n" +
	"\tresources\x18\x03 \x01(\v2#.nimbuscore.v1.ResourceRequirementsR\tresources\x12I\n" +
	"\x10security_context\x18\x04 \x01(\v2\x1e.nimbuscore.v1.SecurityContextR\x0fsecurityContext\x12\x18\n" +
	"\acommand\x18\x05 \x03(\tR\acommand\x12(\n" +
	"\x10wasm_module_path\x18\x06 \x01(\tR\x0ewasmModulePath\x12'\n" +
	"\x0fcontainer_ports\x18\a \x03(\x05R\x0econtainerPorts\x123\n" +
	"\x03env\x18\b \x03(\v2!.nimbuscore.v1.Container.EnvEntryR\x03env\x12=\n" +
	"\fbuild_source\x18\t \x01(\v2\x1a.nimbuscore.v1.BuildSourceR\vbuildSource\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x01\n" +
	"\aPodSpec\x128\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x18.nimbuscore.v1.ContainerR\n" +
	"containers\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x124\n" +
	"\avolumes\x18\x03 \x03(\v2\x1a.nimbuscore.v1.VolumeMountR\avolumes\x12C\n" +
	"\x0erestart_policy\x18\x04 \x01(\x0e2\x1c.nimbuscore.v1.RestartPolicyR\rrestartPolicy\"\xe1\x01\n" +
	"\tPodStatus\x12-\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x17.nimbuscore.v1.PodPhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\n" +
	"conditions\x18\x03 \x03(\v2\x18.nimbuscore.v1.ConditionR\n" +
	"conditions\x12#\n" +
	"\rrestart_count\x18\x04 \x01(\x05R\frestartCount\x12,\n" +
	"\x12memory_usage_bytes\x18\x05 \x01(\x03R\x10memoryUsageBytes\"\x9a\x01\n" +
	"\x03Pod\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.nimbuscore.v1.ObjectMetaR\bmetadata\x12*\n" +
	"\x04spec\x18\x02 \x01(\v2\x16.nimbuscore.v1.PodSpecR\x04spec\x120\n" +
	"\x06status\x18\x03 \x01(\v2\x18.nimbuscore.v1.PodStatusR\x06status*\x83\x01\n" +
	"\rRestartPolicy\x12\x1e\n" +
	"\x1aRESTART_POLICY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RESTART_POLICY_ALWAYS\x10\x01\x12\x1d\n" +
	"\x19RESTART_POLICY_ON_FAILURE\x10\x02\x12\x18\n" +
	"\x14RESTART_POLICY_NEVER\x10\x03*\x99\x01\n" +
	"\bPodPhase\x12\x19\n" +
	"\x15POD_PHASE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11POD_PHASE_PENDING\x10\x01\x12\x15\n" +
	"\x11POD_PHASE_RUNNING\x10\x02\x12\x17\n" +
	"\x13POD_PHASE_SUCCEEDED\x10\x03\x12\x14\n" +
	"\x10POD_PHASE_FAILED\x10\x04\x12\x15\n" +
	"\x11POD_PHASE_UNKNOWN\x10\x05B/Z-github.com/gh0st-nemesis/nimbuscore/api/v1;v1b\x06proto3"

var (
	file_pod_proto_rawDescOnce sync.Once
	file_pod_proto_rawDescData []byte
)

func file_pod_proto_rawDescGZIP() []byte {
	file_pod_proto_rawDescOnce.Do(func() {
		file_pod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pod_proto_rawDesc), len(file_pod_proto_rawDesc)))
	})
	return file_pod_proto_rawDescData
}

var file_pod_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pod_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pod_proto_goTypes = []any{
	(RestartPolicy)(0),           // 0: nimbuscore.v1.RestartPolicy
	(PodPhase)(0),                // 1: nimbuscore.v1.PodPhase
	(*SecurityContext)(nil),      // 2: nimbuscore.v1.SecurityContext
	(*BuildSource)(nil),          // 3: nimbuscore.v1.BuildSource
	(*Container)(nil),            // 4: nimbuscore.v1.Container
	(*PodSpec)(nil),              // 5: nimbuscore.v1.PodSpec
	(*PodStatus)(nil),            // 6: nimbuscore.v1.PodStatus
	(*Pod)(nil),                  // 7: nimbuscore.v1.Pod
	nil,                          // 8: nimbuscore.v1.Container.EnvEntry
	(*ResourceRequirements)(nil), // 9: nimbuscore.v1.ResourceRequirements
	(*VolumeMount)(nil),          // 10: nimbuscore.v1.VolumeMount
	(*Condition)(nil),            // 11: nimbuscore.v1.Condition
	(*ObjectMeta)(nil),           // 12: nimbuscore.v1.ObjectMeta
}
var file_pod_proto_depIdxs = []int32{
	9,  // 0: nimbuscore.v1.Container.resources:type_name -> nimbuscore.v1.ResourceRequirements
	2,  // 1: nimbuscore.v1.Container.security_context:type_name -> nimbuscore.v1.SecurityContext
	8,  // 2: nimbuscore.v1.Container.env:type_name -> nimbuscore.v1.Container.EnvEntry
	3,  // 3: nimbuscore.v1.Container.build_source:type_name -> nimbuscore.v1.BuildSource
	4,  // 4: nimbuscore.v1.PodSpec.containers:type_name -> nimbuscore.v1.Container
	10, // 5: nimbuscore.v1.PodSpec.volumes:type_name -> nimbuscore.v1.VolumeMount
	0,  // 6: nimbuscore.v1.PodSpec.restart_policy:type_name -> nimbuscore.v1.RestartPolicy
	1,  // 7: nimbuscore.v1.PodStatus.phase:type_name -> nimbuscore.v1.PodPhase
	11, // 8: nimbuscore.v1.PodStatus.conditions:type_name -> nimbuscore.v1.Condition
	12, // 9: nimbuscore.v1.Pod.metadata:type_name -> nimbuscore.v1.ObjectMeta
	5,  // 10: nimbuscore.v1.Pod.spec:type_name -> nimbuscore.v1.PodSpec
	6,  // 11: nimbuscore.v1.Pod.status:type_name -> nimbuscore.v1.PodStatus
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pod_proto_init() }
func file_pod_proto_init() {
	if File_pod_proto != nil {
		return
	}
	file_common_proto_init()
	file_volume_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pod_proto_rawDesc), len(file_pod_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pod_proto_goTypes,
		DependencyIndexes: file_pod_proto_depIdxs,
		EnumInfos:         file_pod_proto_enumTypes,
		MessageInfos:      file_pod_proto_msgTypes,
	}.Build()
	File_pod_proto = out.File
	file_pod_proto_goTypes = nil
	file_pod_proto_depIdxs = nil
}
