syntax = "proto3";

package nimbuscore.v1;

import "common.proto";

option go_package = "github.com/gh0st-nemesis/nimbuscore/api/v1;v1";

message Secret {
  ObjectMeta metadata = 1;
  map<string, bytes> data = 2;
}

service SecretService {
  rpc CreateSecret(CreateSecretRequest) returns (Secret);
  rpc GetSecret(GetSecretRequest) returns (Secret);
  rpc ListSecrets(ListSecretsRequest) returns (ListSecretsResponse);
  rpc DeleteSecret(DeleteSecretRequest) returns (DeleteSecretResponse);
}

message CreateSecretRequest {
  Secret secret = 1;
}

message GetSecretRequest {
  string namespace = 1;
  string name = 2;
}

message ListSecretsRequest {
  string namespace = 1;
}

message ListSecretsResponse {
  repeated Secret items = 1;
}

message DeleteSecretRequest {
  string namespace = 1;
  string name = 2;
}

message DeleteSecretResponse {}
