// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: volume.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VolumePhase int32

const (
	VolumePhase_VOLUME_PHASE_UNSPECIFIED VolumePhase = 0
	VolumePhase_VOLUME_PHASE_PENDING     VolumePhase = 1
	VolumePhase_VOLUME_PHASE_BOUND       VolumePhase = 2
	VolumePhase_VOLUME_PHASE_FAILED      VolumePhase = 3
)

// Enum value maps for VolumePhase.
var (
	VolumePhase_name = map[int32]string{
		0: "VOLUME_PHASE_UNSPECIFIED",
		1: "VOLUME_PHASE_PENDING",
		2: "VOLUME_PHASE_BOUND",
		3: "VOLUME_PHASE_FAILED",
	}
	VolumePhase_value = map[string]int32{
		"VOLUME_PHASE_UNSPECIFIED": 0,
		"VOLUME_PHASE_PENDING":     1,
		"VOLUME_PHASE_BOUND":       2,
		"VOLUME_PHASE_FAILED":      3,
	}
)

func (x VolumePhase) Enum() *VolumePhase {
	p := new(VolumePhase)
	*p = x
	return p
}

func (x VolumePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VolumePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_volume_proto_enumTypes[0].Descriptor()
}

func (VolumePhase) Type() protoreflect.EnumType {
	return &file_volume_proto_enumTypes[0]
}

func (x VolumePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VolumePhase.Descriptor instead.
func (VolumePhase) EnumDescriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{0}
}

type VolumeSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestedBytes int64                  `protobuf:"varint,1,opt,name=requested_bytes,json=requestedBytes,proto3" json:"requested_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VolumeSpec) Reset() {
	*x = VolumeSpec{}
	mi := &file_volume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeSpec) ProtoMessage() {}

func (x *VolumeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeSpec.ProtoReflect.Descriptor instead.
func (*VolumeSpec) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{0}
}

func (x *VolumeSpec) GetRequestedBytes() int64 {
	if x != nil {
		return x.RequestedBytes
	}
	return 0
}

type VolumeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         VolumePhase            `protobuf:"varint,1,opt,name=phase,proto3,enum=nimbuscore.v1.VolumePhase" json:"phase,omitempty"`
	CapacityBytes int64                  `protobuf:"varint,2,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	NodeName      string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeStatus) Reset() {
	*x = VolumeStatus{}
	mi := &file_volume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeStatus) ProtoMessage() {}

func (x *VolumeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeStatus.ProtoReflect.Descriptor instead.
func (*VolumeStatus) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{1}
}

func (x *VolumeStatus) GetPhase() VolumePhase {
	if x != nil {
		return x.Phase
	}
	return VolumePhase_VOLUME_PHASE_UNSPECIFIED
}

func (x *VolumeStatus) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *VolumeStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VolumeStatus) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ObjectMeta            `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *VolumeSpec            `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *VolumeStatus          `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_volume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{2}
}

func (x *Volume) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Volume) GetSpec() *VolumeSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Volume) GetStatus() *VolumeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeName    string                 `protobuf:"bytes,1,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	MountPath     string                 `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_volume_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{3}
}

func (x *VolumeMount) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *VolumeMount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *VolumeMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type CreateVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        *Volume                `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeRequest) Reset() {
	*x = CreateVolumeRequest{}
	mi := &file_volume_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeRequest) ProtoMessage() {}

func (x *CreateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVolumeRequest) GetVolume() *Volume {
	if x != nil {
		return x.Volume
	}
	return nil
}

type GetVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVolumeRequest) Reset() {
	*x = GetVolumeRequest{}
	mi := &file_volume_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVolumeRequest) ProtoMessage() {}

func (x *GetVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVolumeRequest.ProtoReflect.Descriptor instead.
func (*GetVolumeRequest) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{5}
}

func (x *GetVolumeRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListVolumesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesRequest) Reset() {
	*x = ListVolumesRequest{}
	mi := &file_volume_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesRequest) ProtoMessage() {}

func (x *ListVolumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesRequest.ProtoReflect.Descriptor instead.
func (*ListVolumesRequest) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{6}
}

func (x *ListVolumesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ListVolumesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Volume              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesResponse) Reset() {
	*x = ListVolumesResponse{}
	mi := &file_volume_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesResponse) ProtoMessage() {}

func (x *ListVolumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesResponse.ProtoReflect.Descriptor instead.
func (*ListVolumesResponse) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{7}
}

func (x *ListVolumesResponse) GetItems() []*Volume {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeRequest) Reset() {
	*x = DeleteVolumeRequest{}
	mi := &file_volume_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeRequest) ProtoMessage() {}

func (x *DeleteVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeRequest.ProtoReflect.Descriptor instead.
func (*DeleteVolumeRequest) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteVolumeRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DeleteVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeResponse) Reset() {
	*x = DeleteVolumeResponse{}
	mi := &file_volume_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeResponse) ProtoMessage() {}

func (x *DeleteVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeResponse.ProtoReflect.Descriptor instead.
func (*DeleteVolumeResponse) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{9}
}

var File_volume_proto protoreflect.FileDescriptor

const file_volume_proto_rawDesc = "" +
	"\n" +
	"\fvolume.proto\x12\rnimbuscore.v1\x1a\fcommon.proto\"5\n" +
	"\n" +
	"VolumeSpec\x12'\n" +
	"\x0frequested_bytes\x18\x01 \x01(\x03R\x0erequestedBytes\"\x9e\x01\n" +
	"\fVolumeStatus\x120\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x1a.nimbuscore.v1.VolumePhaseR\x05phase\x12%\n" +
	"\x0ecapacity_bytes\x18\x02 \x01(\x03R\rcapacityBytes\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\"\xa3\x01\n" +
	"\x06Volume\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x19.nimbuscore.v1.ObjectMetaR\bmetadata\x12-\n" +
	"\x04spec\x18\x02 \x01(\v2\x19.nimbuscore.v1.VolumeSpecR\x04spec\x123\n" +
	"\x06status\x18\x03 \x01(\v2\x1b.nimbuscore.v1.VolumeStatusR\x06status\"j\n" +
	"\vVolumeMount\x12\x1f\n" +
	"\vvolume_name\x18\x01 \x01(\tR\n" +
	"volumeName\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"D\n" +
	"\x13CreateVolumeRequest\x12-\n" +
	"\x06volume\x18\x01 \x01(\v2\x15.nimbuscore.v1.VolumeR\x06volume\"D\n" +
	"\x10GetVolumeRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"2\n" +
	"\x12ListVolumesRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"B\n" +
	"\x13ListVolumesResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.nimbuscore.v1.VolumeR\x05items\"G\n" +
	"\x13DeleteVolumeRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x16\n" +
	"\x14DeleteVolumeResponse*v\n" +
	"\vVolumePhase\x12\x1c\n" +
	"\x18VOLUME_PHASE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14VOLUME_PHASE_PENDING\x10\x01\x12\x16\n" +
	"\x12VOLUME_PHASE_BOUND\x10\x02\x12\x17\n" +
	"\x13VOLUME_PHASE_FAILED\x10\x032\xce\x02\n" +
	"\rVolumeService\x12I\n" +
	"\fCreateVolume\x12\".nimbuscore.v1.CreateVolumeRequest\x1a\x15.nimbuscore.v1.Volume\x12C\n" +
	"\tGetVolume\x12\x1f.nimbuscore.v1.GetVolumeRequest\x1a\x15.nimbuscore.v1.Volume\x12T\n" +
	"\vListVolumes\x12!.nimbuscore.v1.ListVolumesRequest\x1a\".nimbuscore.v1.ListVolumesResponse\x12W\n" +
	"\fDeleteVolume\x12\".nimbuscore.v1.DeleteVolumeRequest\x1a#.nimbuscore.v1.DeleteVolumeResponseB/Z-github.com/gh0st-nemesis/nimbuscore/api/v1;v1b\x06proto3"

var (
	file_volume_proto_rawDescOnce sync.Once
	file_volume_proto_rawDescData []byte
)

func file_volume_proto_rawDescGZIP() []byte {
	file_volume_proto_rawDescOnce.Do(func() {
		file_volume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_volume_proto_rawDesc), len(file_volume_proto_rawDesc)))
	})
	return file_volume_proto_rawDescData
}

var file_volume_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_volume_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_volume_proto_goTypes = []any{
	(VolumePhase)(0),             // 0: nimbuscore.v1.VolumePhase
	(*VolumeSpec)(nil),           // 1: nimbuscore.v1.VolumeSpec
	(*VolumeStatus)(nil),         // 2: nimbuscore.v1.VolumeStatus
	(*Volume)(nil),               // 3: nimbuscore.v1.Volume
	(*VolumeMount)(nil),          // 4: nimbuscore.v1.VolumeMount
	(*CreateVolumeRequest)(nil),  // 5: nimbuscore.v1.CreateVolumeRequest
	(*GetVolumeRequest)(nil),     // 6: nimbuscore.v1.GetVolumeRequest
	(*ListVolumesRequest)(nil),   // 7: nimbuscore.v1.ListVolumesRequest
	(*ListVolumesResponse)(nil),  // 8: nimbuscore.v1.ListVolumesResponse
	(*DeleteVolumeRequest)(nil),  // 9: nimbuscore.v1.DeleteVolumeRequest
	(*DeleteVolumeResponse)(nil), // 10: nimbuscore.v1.DeleteVolumeResponse
	(*ObjectMeta)(nil),           // 11: nimbuscore.v1.ObjectMeta
}
var file_volume_proto_depIdxs = []int32{
	0,  // 0: nimbuscore.v1.VolumeStatus.phase:type_name -> nimbuscore.v1.VolumePhase
	11, // 1: nimbuscore.v1.Volume.metadata:type_name -> nimbuscore.v1.ObjectMeta
	1,  // 2: nimbuscore.v1.Volume.spec:type_name -> nimbuscore.v1.VolumeSpec
	2,  // 3: nimbuscore.v1.Volume.status:type_name -> nimbuscore.v1.VolumeStatus
	3,  // 4: nimbuscore.v1.CreateVolumeRequest.volume:type_name -> nimbuscore.v1.Volume
	3,  // 5: nimbuscore.v1.ListVolumesResponse.items:type_name -> nimbuscore.v1.Volume
	5,  // 6: nimbuscore.v1.VolumeService.CreateVolume:input_type -> nimbuscore.v1.CreateVolumeRequest
	6,  // 7: nimbuscore.v1.VolumeService.GetVolume:input_type -> nimbuscore.v1.GetVolumeRequest
	7,  // 8: nimbuscore.v1.VolumeService.ListVolumes:input_type -> nimbuscore.v1.ListVolumesRequest
	9,  // 9: nimbuscore.v1.VolumeService.DeleteVolume:input_type -> nimbuscore.v1.DeleteVolumeRequest
	3,  // 10: nimbuscore.v1.VolumeService.CreateVolume:output_type -> nimbuscore.v1.Volume
	3,  // 11: nimbuscore.v1.VolumeService.GetVolume:output_type -> nimbuscore.v1.Volume
	8,  // 12: nimbuscore.v1.VolumeService.ListVolumes:output_type -> nimbuscore.v1.ListVolumesResponse
	10, // 13: nimbuscore.v1.VolumeService.DeleteVolume:output_type -> nimbuscore.v1.DeleteVolumeResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_volume_proto_init() }
func file_volume_proto_init() {
	if File_volume_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_volume_proto_rawDesc), len(file_volume_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_volume_proto_goTypes,
		DependencyIndexes: file_volume_proto_depIdxs,
		EnumInfos:         file_volume_proto_enumTypes,
		MessageInfos:      file_volume_proto_msgTypes,
	}.Build()
	File_volume_proto = out.File
	file_volume_proto_goTypes = nil
	file_volume_proto_depIdxs = nil
}
